name: API Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cypress.io
        uses: cypress-io/github-action@v5
        with: 
             start: npm start
        
