on: [push]
permissions:
  contents: read  # Required to read the repository contents
  pull-requests: write  # Required if you need to comment on pull requests
  security-events: write  # Required for security tools like OWASP ZAP
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main # Ensure this matches your branch name
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d'